### ISSUE TITLE
Weeb Central error  Cannot find "div">a"

### ISSUE THREAD

**Issue by VisualWarlock** [KotatsuApp/kotatsu-parsers#1503]
### Source information

weebcentral.com

### Steps to reproduce

1. search for any manga title with weebcentral enabled as source
2. weebcentral presents error message  Cannot find "div">a"
3.  Cannot find "div">a"   error is also present when opening the weebcentral page inside the app.

### Kotatsu version

7.7.11

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> weebcentral.com
> 
> ### Steps to reproduce
> 1. search for any manga title with weebcentral enabled as source
> 2. weebcentral presents error message  Cannot find "div">a"
> 3. Cannot find "div">a"   error is also present when opening the weebcentral page inside the app.
> 
> ### Kotatsu version
> 7.7.11
> 
> ### Android version
> _No response_
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Fixed #1502

**Comment by VisualWarlock** [comment]
Sorry, I'm new to the way github is arranged, does this mean the issue was resolved? I am still getting it in my app, is the fix in the latest beta? an upcoming update to the apk?

**Comment by dragonx943** [comment]
> Sorry, I'm new to the way github is arranged, does this mean the issue was resolved? I am still getting it in my app, is the fix in the latest beta? an upcoming update to the apk?

Fixed in latest nightly build or u have to wait next stable release
